name: Basic Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: akash.gundu@gramener.com
        run: echo "Hello, world!"
